name: .NET with Docker Deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        
    - name: Restore dependencies
      working-directory: ./ImmersiHome-API
      run: dotnet restore
      
    - name: Build
      working-directory: ./ImmersiHome-API
      run: dotnet build --no-restore
      
    - name: Test
      working-directory: ./ImmersiHome-API
      run: dotnet test --no-build --verbosity normal

    - name: Publish
      working-directory: ./ImmersiHome-API
      run: dotnet publish -c Release -o ./publish

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build Docker Image
      working-directory: ./ImmersiHome-API
      run: |
        docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/immersihome-api:latest .

    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/immersihome-api:latest

    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/immersihome-api:latest
          docker stop immersihome-api || true
          docker rm immersihome-api || true
          docker run -d --name immersihome-api -p 80:80 ${{ secrets.DOCKER_HUB_USERNAME }}/immersihome-api:latest
