name: .NET with Docker Deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        
    # - name: Restore dependencies
    #   working-directory: ./src/BoligPletten.Api
    #   run: dotnet restore
      
    # - name: Build
    #   working-directory: ./src/BoligPletten.Api
    #   run: dotnet build --no-restore
      
    # - name: Test
    #   working-directory: ./src/BoligPletten.Api
    #   run: dotnet test --no-build --verbosity normal

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and Push Docker Image
      run: |
        # Navigate to the repository root
        cd $GITHUB_WORKSPACE
        
        # Build the Docker image with a proper context
        docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/immersihome-api:latest -f ./src/BoligPletten.Api/Dockerfile .
        
        # Push the Docker image
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/immersihome-api:latest