# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        
    - name: Restore dependencies
      working-directory: ./ImmersiHome-API
      run: dotnet restore
      
    - name: Build
      working-directory: ./ImmersiHome-API
      run: dotnet build --no-restore
      
    - name: Test
      working-directory: ./ImmersiHome-API
      run: dotnet test --no-build --verbosity normal

    - name: Publish
      working-directory: ./ImmersiHome-API
      run: dotnet publish -c Release -o ./publish

    - name: Deploy to Server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "./ImmersiHome-API/publish/*"
        target: ${{ secrets.DEPLOYMENT_PATH }}
